apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" . }}
  name: {{ .Values.metadata.name }}-service
spec:
  ports:
  - name: {{ .Values.metadata.name }}-port
    port: {{ .Values.service.port}}
    protocol: {{ .Values.service.protocol}}
    targetPort: {{ .Values.service.port}}
    nodePort: {{ .Values.service.nodeport}}
  selector:
    {{- include "labels" . }}
  type: NodePort
status:
  loadBalancer: {}